@baseUrl = http://localhost:5000

## Home route
GET http://localhost:5000/

###


## Get all vehicles
GET http://localhost:5000/vehicles

###

## Get a vehicle by ID
GET http://localhost:5000/vehicles/3

###

## Create a new vehicle
POST http://localhost:5000/vehicles
Content-Type: application/json

{
    "make": "BYD",
    "model": "Shark 6",
    "year": 2026,
    "vin": "BYD1234567890"
}

###