@baseUrl = http://localhost:5000
@apiV1 = http://localhost:5000/api/v1

## Home route
GET {{baseUrl}}/

###

## Health check
GET {{baseUrl}}/health

###

## Get all vehicles
GET {{apiV1}}/vehicles

###

## Get a vehicle by ID
GET {{apiV1}}/vehicles/3

###

## Create a new vehicle
POST {{apiV1}}/vehicles
Content-Type: application/json

{
    "make": "Benz",
    "model": "C-Class",
    "year": 2025,
    "vin": "WDB1234567855"
}

###

## Update an existing vehicle
PUT {{apiV1}}/vehicles/3
Content-Type: application/json

{
    "make": "BYD",
    "model": "Shark 6",
    "year": 2026,
    "vin": "BYD1234567890"
}

###

## Delete a vehicle
DELETE {{apiV1}}/vehicles/8

###